# Generated by Django 4.1.3 on 2022-11-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
