# Generated by Django 4.1.3 on 2022-11-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_report_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='decs',
            new_name='desc',
        ),
    ]
