# Generated by Django 4.1.3 on 2022-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_decs_report_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='icepops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
